version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - checkout
      - run:
          name: "Primera etapa - Instalacion" 
          command: | 
            echo "Se construye el contenedor"
            node --version
      - run:
          name: "Segunda etapa - Pruebas"
          command: |
            echo "Realizando pruebas"
            cd /home/app
            ls -ltr
workflows:
  build_and_test:
    jobs:
      - build
