version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Primera etapa - Instalacion y construccion" 
          command: | 
            echo "Se construye el contenedor"
            ls -ltr
            docker build -t adimen/app-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM .
      - run:
          name: "Segunda etapa - Ejecucion y Pruebas"
          command: |
            echo "Realizando pruebas"
            docker run -dp 80:3000 --name app -it adimen/app-$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM
            echo "Verifica que esta en ejecucion el contenedor"
            docker ps
            echo "Probando..." 
            curl http://localhost/test
workflows:
  build_and_test:
    jobs:
      - build
