version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Primera etapa - Instalacion y construccion" 
          command: | 
            echo "Se construye el contenedor"
            ls -ltr
            docker run -dp 3000:3000 --name app
      - run:
          name: "Segunda etapa - Ejecucion y Pruebas"
          command: |
            echo "Realizando pruebas"
            docker build -t adimen/app:$CIRCLE_BRANCH .
            wget http://localhost:3000/test
workflows:
  build_and_test:
    jobs:
      - build
