version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.8.0-alpine3.14
    steps:
      - checkout
      - run:
          name: "Build" 
          command: echo "Se construye el contenedor" |
                   node --version
  test:
    docker:
      - image: cimg/node:17.8.0-alpine3.14
    stepd:
      - checkout
      - run: echo "Prueba de ejecucion"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
          