version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Primera etapa - Instalacion y construccion" 
          command: | 
            echo "Se construye el contenedor"
            ls -ltr
            docker build -t adimen/app:$CIRCLE_BRANCH .
      - run:
          name: "Segunda etapa - Ejecucion y Pruebas"
          command: |
            echo "Realizando pruebas"
            docker run -dp 3000:3000 --name app -it adimen/app:$CIRCLE_BRANCH
            echo "Verfivica que corre primero"
            docker ps
            echo "Probando..." 
            curl http://localhost:3000/test
workflows:
  build_and_test:
    jobs:
      - build
