version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - checkout
      - run:
          name: "Primera etapa - Instalacion" 
          command: | 
            echo "Se construye el contenedor"
            node --version
      - run:
          name: "Segunda etapa - Pruebas"
          command: |
            echo "Realizando pruebas"
            cd app
            npm start
            wget http://127.0.0.1:3000/test
workflows:
  build_and_test:
    jobs:
      - build
